<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>FH.Customers.Api</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.4">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Core\FH.Customers.Application\FH.Customers.Application.csproj" />
    <ProjectReference Include="..\..\Infrastructure\FH.Customers.Persistence\FH.Customers.Persistence.csproj" />
    <ProjectReference Include="..\..\Infrastructure\FH.Customers.Infrastructure\FH.Customers.Infrastructure.csproj" />
  </ItemGroup>

</Project>
