// <auto-generated />
using System;
using System.Collections.Generic;
using FH.Modules.CustomerPlans.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FH.Modules.CustomerPlans.infrastructure.Migrations
{
    [DbContext(typeof(CustomerPlansDbContext))]
    partial class CustomerPlansDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FH.Modules.CustomerPlans.Domain.Subscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<Guid>("ExternalPlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("external_plan_id");

                    b.Property<int>("MaxBeneficiaries")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("max_beneficiaries");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("ACTIVE")
                        .HasColumnName("status");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Period", "FH.Modules.CustomerPlans.Domain.Subscription.Period#SubscriptionPeriod", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateOnly?>("EndDate")
                                .HasColumnType("date")
                                .HasColumnName("end_date");

                            b1.Property<DateOnly>("StartDate")
                                .HasColumnType("date")
                                .HasColumnName("start_date");
                        });

                    b.HasKey("Id");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("IX_customer_subscriptions_customer_id");

                    b.ToTable("customer_subscriptions", null, t =>
                        {
                            t.HasCheckConstraint("CK_customer_subscriptions_dates", "end_date IS NULL OR end_date >= start_date");

                            t.HasCheckConstraint("CK_customer_subscriptions_max_beneficiaries", "max_beneficiaries >= 1");

                            t.HasCheckConstraint("CK_customer_subscriptions_status", "status IN ('ACTIVE', 'SUSPENDED', 'CANCELLED', 'EXPIRED')");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
